on: [push]

name: CI

jobs:
  build-zkgroup:
    name: build zkgroup
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: |
          cargo install cross
          cd lib/zkgroup/
          cross build --target aarch64-unknown-linux-gnu
